// Generated by CoffeeScript 2.0.0-beta8
void function () {
  var MONGOLAB_STATUS_URL, request;
  request = require('request');
  MONGOLAB_STATUS_URL = "https://api.mongolab.com/api/1/clusters/rs-dbh97/databases/mongolab-status/collections/public-status-events?s={'timeStarted':%20-1}&apiKey=4f023946e4b0d227da1b51d8";
  module.exports.mongolab = function (req, res) {
    return req = request(MONGOLAB_STATUS_URL, function (error, response, body) {
      var line, lines, proje;
      if (error)
        throw error;
      if (!(response.statusCode === 200))
        throw new Error('status ' + response.statusCode);
      lines = JSON.parse(body);
      proje = function (accum$) {
        for (var i$ = 0, length$ = lines.length; i$ < length$; ++i$) {
          line = lines[i$];
          accum$.push({
            time: Date(line.timeStarted.$date),
            details: line.details
          });
        }
        return accum$;
      }.call(this, []);
      return res.end(proje, 200);
    });
  };
}.call(this);
