// Generated by CoffeeScript 2.0.0-beta8
void function () {
  var async, cheerio, format, KZRADIO_BASE_URL, request;
  request = require('request');
  cheerio = require('cheerio');
  async = require('async');
  format = require('util').format;
  KZRADIO_BASE_URL = 'http://kzradio.net/';
  module.exports.current = function (cb) {
    return request(KZRADIO_BASE_URL, function (error, response, body) {
      var $, $show, $splash;
      if (error)
        throw error;
      if (!(response.statusCode === 200))
        throw new Error('status ' + response.statusCode);
      $ = cheerio.load(body);
      $show = $('.show-contents');
      $show.find('.avatars, #content-container, .item-blah').remove();
      $splash = $show.find('.special-splash');
      $show.append($splash.find('img'));
      $splash.remove();
      $show.find('h3 span').each(function (i, el) {
        var $el;
        $el = $(el);
        return $show.prepend('<pre id=' + $el.attr('id') + '>' + $el.text() + '</pre>');
      });
      return cb($show.html());
    });
  };
}.call(this);

//# sourceMappingURL=kzradio.map
